name: Django CI - Migrations and Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona el codi del repositori
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Instal·la Python 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3. Instal·la Django i altres dependències
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django

    # 4. Executa les migracions
    - name: Run migrations
      run: |
        python manage.py makemigrations --noinput
        python manage.py migrate --noinput
      env:
        DJANGO_SETTINGS_MODULE: blog.settings  # Defineix la variable d'entorn per a les migracions

    # 5. Genera documentació per a blog/views.py amb pydoc
    - name: Generate documentation for views.py
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python -m pydoc -w blog.views  # Genera views.html a l'arrel
      env:
        DJANGO_SETTINGS_MODULE: blog.settings  # Defineix la variable d'entorn per a pydoc

    # 6. Genera documentació per a blog/models.py amb pydoc
    - name: Generate documentation for models.py
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python -m pydoc -w blog.models  # Genera models.html a l'arrel
      env:
        DJANGO_SETTINGS_MODULE: blog.settings  # Defineix la variable d'entorn per a pydoc
