name: Django CI - Migrations and Documentation

# Quan s'executarà el workflow
on:
  push:
    branches: [ main ]  # Executa el workflow quan es fa push a la branca 'main'
  pull_request:
    branches: [ main ]  # Executa el workflow quan es crea un PR cap a 'main'

# Tasques a executar
jobs:
  build:
    runs-on: ubuntu-latest  # Executa el workflow en una màquina Ubuntu

    steps:
    # 1. Clona el codi del repositori
    - name: Checkout code
      uses: actions/checkout@v4  # Aquesta acció clona el repositori

    # 2. Instal·la Python 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3. Instal·la Django i altres dependències
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django  # Instal·la Django
        # Si tens un fitxer requirements.txt, pots fer:
        # pip install -r requirements.txt

    # 4. Executa les migracions
    - name: Run migrations
      run: |
        python manage.py makemigrations --noinput
        python manage.py migrate --noinput

    # 5. Genera documentació per a blog/views.py amb pydoc
    - name: Generate documentation for views.py
      run: |
        python -m pydoc -w ./blog/views.py  # Genera views.html a l'arrel

    # 6. Genera documentació per a blog/models.py amb pydoc
    - name: Generate documentation for models.py
      run: |
        python -m pydoc -w ./blog/models.py  # Genera models.html a l'arrel
